version: '3.1'
volumes:
  data:
  capnp-secrets:
secrets:
  ocaml-ci-github-key:
    external: true
  ocaml-ci-ssh-key:
    external: true
  ocaml-ci-oauth:
    external: true
services:
  ci:
    image: ocaml-ci-service
    command: --github-app-id 39151 --github-private-key-file /run/secrets/ocaml-ci-github-key --github-account-whitelist "talex5,ocurrent,ocaml,mirage,avsm,samoht,kit-ty-kate,tarides,aantron,ocamllabs,realworldocaml,NathanReb,0install,gpetiot,ocaml-ppx,CraigFe,pascutto,julow,vocal-project,vbmithr,gs0510,magnuss,dune-universe" --confirm above-average --confirm-auto-release 120 --capnp-address=tcp:ci.ocamllabs.io:8102 --github-oauth /run/secrets/ocaml-ci-oauth
    environment:
      - "CI_PROFILE=production"
      - "DOCKER_BUILDKIT=1"
      - "PROGRESS_NO_TRUNC=1"
    ports:
      - '8102:9000'
    volumes:
      - 'data:/var/lib/ocurrent'
      - '/var/run/docker.sock:/var/run/docker.sock'
      - 'capnp-secrets:/capnp-secrets'
    secrets:
      - 'ocaml-ci-oauth'
      - 'ocaml-ci-github-key'
      - source: 'ocaml-ci-ssh-key'
        mode: 0400
    sysctls:
      - 'net.ipv4.tcp_keepalive_time=60'
  web:
    image: ocaml-ci-web
    command: --backend /capnp-secrets/ocaml-ci-admin.cap --listen-prometheus=9090
    volumes:
      - 'capnp-secrets:/capnp-secrets:ro'
    sysctls:
      - 'net.ipv4.tcp_keepalive_time=60'
